# Generated by Django 2.1 on 2020-03-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='itemdid',
            new_name='itemid',
        ),
    ]
