# Generated by Django 2.1 on 2020-03-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200324_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='customerid',
            new_name='customerId',
        ),
    ]
